

CREATE OR REPLACE TRIGGER trg_users_updated_at
BEFORE UPDATE ON USERS
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_products_updated_at
BEFORE UPDATE ON PRODUCTS
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_orders_updated_at
BEFORE UPDATE ON ORDERS
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_order_items_updated_at
BEFORE UPDATE ON ORDER_ITEMS
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSDATE;
END;
/